services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLSERVER_USER=your_user
      - SQLSERVER_PASSWORD=your_password
      - SQLSERVER_DB=parsing
      - SQLSERVER_SERVER=db
    volumes:
      - .:/app

