namespace ParsingProject.DAL.Entities;

public static class Reactions
{
    public static Dictionary<string, string> ReactionsMap = new()
    {
        { "👍", "thumbs up" },
        { "👎", "thumbs down" },
        { "❤", "red heart" },
        { "🔥", "fire" },
        { "🥰", "smiling face" },
        { "👏", "clapping hands" },
        { "😁", "grinning face" },
        { "🤔", "thinking face" },
        { "🤯", "exploding head" },
        { "😱", "scream" },
        { "🤬", "face with symbols" },
        { "😢", "crying face" },
        { "🎉", "party popper" },
        { "🤩", "star-struck" },
        { "🤮", "face vomiting" },
        { "💩", "pile of poo" },
        { "🙏", "folded hands" },
        { "👌", "ok hand" },
        { "🕊", "dove of peace" },
        { "🤡", "clown face" },
        { "🥱", "yawning face" },
        { "🥴", "woozy face" },
        { "😍", "smiling face with heart-shaped eyes" },
        { "🐳", "spouting whale" },
        { "❤‍🔥", "heart on fire" },
        { "🌚", "new moon face" },
        { "🌭", "hot dog" },
        { "💯", "hundred points" },
        { "🤣", "rolling on the floor laughing" },
        { "⚡", "high voltage" },
        { "🍌", "banana" },
        { "🏆", "trophy" },
        { "💔", "broken heart" },
        { "🤨", "face with raised eyebrow" },
        { "😐", "neutral face" },
        { "🍓", "strawberry" },
        { "🍾", "bottle with popping cork" },
        { "💋", "kiss mark" },
        { "🖕", "middle finger" },
        { "😈", "smiling face with horns" },
        { "😴", "sleeping face" },
        { "😭", "loudly crying face" },
        { "🤓", "nerd face" },
        { "👻", "ghost" },
        { "👨‍💻", "man technologist" },
        { "👀", "eyes" },
        { "🎃", "jack-o-lantern" },
        { "🙈", "see-no-evil" },
        { "😇", "smiling face with halo" },
        { "😨", "fearful face" },
        { "🤝", "handshake" },
        { "✍", "writing hand" },
        { "🤗", "hugging face" },
        { "🫡", "saluting face" },
        { "🎅", "father christmas" },
        { "🎄", "christmas tree" },
        { "☃", "snowman" },
        { "💅", "nail polish" },
        { "🤪", "zany face" },
        { "🗿", "moyai" },
        { "🆒", "cool button" },
        { "💘", "heart with arrow" },
        { "🙉", "hear no evil monkey" },
        { "🦄", "unicorn" },
        { "😘", "face blowing a kiss" },
        { "💊", "pill" },
        { "🙊", "speak no evil monkey" },
        { "😎", "smiling face with sunglasses" },
        { "👾", "alien monster" },
        { "🤷‍♂", "man shrugging" },
        { "🤷", "person shrugging" },
        { "🤷‍♀", "woman shrugging" },
        { "😡", "enraged face" }
    };
}