name: Docker images
on:
  push:
    branches: [ main ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend docker image
        uses: docker/build-push-action@v3
        with:
          context: ./FrontendProject
          file: ./FrontendProject/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/analysis_frontend-project:latest
          push: true

      - name: Build and push parsing project docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ParsingProject/ParsingProject
          file: ./ParsingProject/ParsingProject/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/analysis_parsing-project:latest
          push: true
          build-args: |
            PROJECT_PORT=5050

      - name: Build and push analysis project docker image
        uses: docker/build-push-action@v3
        with:
          context: ./AnalysisProject
          file: ./AnalysisProject/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/analysis_analysis-project:latest
          push: true

  